//
// Created by charm on 17/10/2023.
//

#ifndef PROJECT12_FRIENDFUNCTION_RANK_H
#define PROJECT12_FRIENDFUNCTION_RANK_H

enum Rank{
    ACE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING
};

#endif //PROJECT12_FRIENDFUNCTION_RANK_H
